export const techColors: Record<string, string> = {
  Astro: "bg-purple-500 text-white",
  TypeScript: "bg-blue-600 text-white",
  JavaScript: "bg-yellow-400 text-black",
  PHP: "bg-orange-400 text-black",
  jQuery: "bg-black text-white",
  React: "bg-blue-500 text-white",
  "Next.js": "bg-black text-white",
  NextJS: "bg-black text-white",
  TailwindCSS: "bg-teal-500 text-white",
  "CSS Modules": "bg-gray-500 text-white",
  Firebase: "bg-yellow-500 text-black",
  Firestore: "bg-orange-500 text-white",
  Redux: "bg-purple-700 text-white",
  "React Context API": "bg-blue-400 text-white",
  "Styled Components": "bg-pink-500 text-white",
  "Firebase Authentication": "bg-red-500 text-white",
  "Google Books API": "bg-green-600 text-white",
};